name: CI/CD

on: [push]

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Publish the new version to npm
        id: publish
        continue-on-error: true
        run: | # Compare the latest version and the current version and publish only if the version changed
          if [ $(npm view branch-scanner version) != $(node -e "console.log(require('./package.json').version)") ]; then npm publish; else exit 1; fi;
          echo ::set-output name=success::$(echo "true")
        if: github.ref == 'refs/heads/master'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: 'marvinpinto/action-automatic-releases@latest'
        if: steps.publish.outputs.success == 'true'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          automatic_release_tag: latest
